'\" t
.\"     Title: plebtrkraw
.\"    Author: Dan Frazier
.\"      Date: 01/23/2017
.\"    Manual: PLEBTracker Manual
.\"  Language: English
.TH "PLEBTRKRAW" "1" "01/23/2017"
.nh
.ad l
.SH "NAME"
plebtrkraw \- Ncurses interface for PLEBTracker
.SH "SYNOPSIS"
.sp
\fBplebtrkraw\fR 
.sp
.SH "DESCRIPTION"
.sp
\fBplebtrkraw\fR is the tracker program. It generally shouldn't be called directly by the user, instead \fBplebtrk\fR is called which starts the daemon and ties that daemon and this tracker together to enable audio playback\&.
.sp
If you do call this, pipe stderr somewhere otherwise it will go to the console and jumble the visual interface.
.sp

.SH "SEE ALSO"
\fBplebtrkdaemon\fR(1), \fBplebtrk\fR(1), \fBplebplay\fR(1), \fBplebitp\fR(1), \fBplebrender\fR(1)
