'\" t
.\"     Title: plebrender
.\"    Author: Dan Frazier
.\"      Date: 04/04/2016
.\"    Manual: PLEBTracker Manual
.\"  Language: English
.TH "PLEBRENDER" "1" "04/04/2016"
.nh
.ad l
.SH "NAME"
plebrender \- [\fIPLEBITP_PARAMS\fR...]
.SH "SYNOPSIS"
.sp
\fBplebrender\fR [\fIMODULE_PATH\fR]
.sp
.SH "DESCRIPTION"
.sp
\fBplebrender\fR renders the output of \fBplebitp\fR directly to a .flac file using flac.
.sp
All parameters are passed to plebitp, to see those parameters, see \fBplebitp\fR(1)\&.
.sp
.SH "SEE ALSO"
\fBplebplay\fR(1), \fBplebitp\fR(1), \fBplebtrkdaemon\fR(1), \fBplebtrkraw\fR(1), \fBplebtrk\fR(1), \fBflac\fR(1)
