'\" t
.\"     Title: plebplay
.\"    Author: Dan Frazier
.\"      Date: 04/04/2016
.\"    Manual: PLEBTracker Manual
.\"  Language: English
.TH "PLEBPLAY" "1" "04/04/2016"
.nh
.ad l
.SH "NAME"
plebplay \- Plays a plb module to default alsa device
.sp
\fBplebplay\fR [\fIPLEBITP_PARAMS...\fR]
.sp
.SH "DESCRIPTION"
.sp
\fBplebplay\fR plays a module created within \fBplebtrk\fR to the default alsa device\&.
.sp
All parameters passed to this script are referred to plebitp, see \fBplebitp\fR(1) for those parameters\&.
.sp
.SH "SEE ALSO"
\fBplebitp\fR(1), \fBplebrender\fR(1), \fBplebtrkdaemon\fR(1), \fBplebtrk\fR(1), \fBplebtrkraw\fR(1)
