#!/bin/bash

if [[ ("$#" < 1) ]] ; then
    echo PLEBInterpreter requires at least one parameter
    exit
fi

LOGPATH="/var/tmp/plebtrk/itplog.log"

echo "" >"$LOGPATH"
plebitp 4800 2>>"$LOGPATH" "$@"  | aplay --rate=48000 --format=S16_LE 2>>"$LOGPATH"


