#!/bin/bash

if [[ ("$#" < 1) ]] ; then
    echo PLEBInterpreter requires at least one parameter
    exit
fi

LOGPATH="/var/tmp/plebtrk/itplog.log"

echo "" >"$LOGPATH"
plebitp 2>>"$LOGPATH" "$@" | aplay --rate=44100 2>>"$LOGPATH"
#plebitpb16 2>>"$LOGPATH" "$@" | aplay --rate=44100 --format=S16_LE 2>>"$LOGPATH"


